### ISSUE TITLE
Verify this github action on the marketplace

### ISSUE THREAD

**Issue by Blitz2145** [authzed/action-spicedb-validate#4]
Can you enable verified creator on this github action? See https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#about-badges-in-github-marketplace

We have some rules turned on that only allow verified github actions on our workflows. We can workaround it for now, not sure how hard it is to get verified, but would be nice to have.

**Comment by jzelinskie** [comment]
I emailed GitHub to learn more about the partner program. I'll provide updates when they respond.

Thanks creating this issue! I had no idea this existed, haha.

**Comment by jzelinskie** [comment]
<img width="364" alt="Screenshot 2023-08-18 at 12 45 50 PM" src="https://github.com/authzed/action-spicedb-validate/assets/343539/1bef6162-8366-4096-88e3-00c21e24111b">
All done!
